/**
 * TaipeiSkySpots - 台北與新北精選 12 大日出/日落火燒雲經典機位數據庫
 */

const TAIPEI_SPOTS = [
  {
    id: 'dadaocheng',
    name: '大稻埕碼頭（延平河濱）',
    category: 'sunset',
    lat: 25.057045046459375,
    lng: 121.50771810454582,
    elevation: 5,
    difficulty: '極易（捷運北門站步行10分）',
    recommendedFocal: '16-35mm 超廣角（河面倒影） / 70-200mm（夕陽帆船）',
    bestAzimuth: '280° - 305°（正西方至西北西）',
    tags: ['河景倒影', '夕陽帆船', '貨櫃市集', '人氣爆棚'],
    description: '台北最具代表性的河畔日落聖地。寬廣的淡水河面能完美倒映漫天晚霞與橘紅火燒雲，前景有復古唐山帆船與藍色公路渡輪，氛圍浪漫。',
    photoTips: '使用低角度三腳架貼近水面拍攝水流倒影，日落後 15 分鐘可利用碼頭燈火銜接藍調時刻。',
    traffic: '搭乘捷運至「北門站」3 號出口或「大橋頭站」步行約 10-15 分鐘；亦可騎乘 YouBike 直達五號水門。'
  },
  {
    id: 'tamsui-fishermans-wharf',
    name: '淡水漁人碼頭與沙崙沙灘',
    category: 'sunset',
    lat: 25.18325188330396,
    lng: 121.41209767613158,
    elevation: 4,
    difficulty: '容易（淡海輕軌/紅26公車）',
    recommendedFocal: '24-70mm, 100-400mm（超大夕陽入海）',
    bestAzimuth: '285° - 315°（西北西出海口）',
    tags: ['海平面落日', '情人橋', '台灣八景', '無遮蔽視野'],
    description: '歷史悠久的台灣八景「淡水夕照」。出海口擁有毫無山體遮蔽的 180 度地平線，當西方海峽出現透光窗時，整片海洋與天幕將被染成金紅烈火。',
    photoTips: '沙崙沙灘退潮時有天然天空之鏡水窪，情人橋木棧道可將白色斜張橋作為火燒雲的前景構圖。',
    traffic: '搭乘捷運淡水線至「淡水站」轉乘紅 26 公車，或搭乘淡海輕軌至「漁人碼頭站」。'
  },
  {
    id: 'xiangshan',
    name: '台北101與象山六巨石',
    category: 'sunset',
    lat: 25.029049882166394,
    lng: 121.57276615548665,
    elevation: 183,
    difficulty: '中等（爬階梯約 20-30 分鐘）',
    recommendedFocal: '16-35mm（全景地標） / 50-85mm（101 特寫）',
    bestAzimuth: '275° - 300°（正西至西北西）',
    tags: ['台北101', '信義區天際線', '國際級地標', '經典明信片'],
    description: '台北明信片第一視角！火燒雲自台北 101 與信義區摩天大樓群後方天際線燃燒漫延，視覺張力無可匹敵。',
    photoTips: '超然亭視野比六巨石更開闊且不易被前方人群遮擋。夏季夕陽角度最靠右，可拍出夕陽自觀音山落下的壯麗構圖。',
    traffic: '搭乘捷運象山線至「象山站」2 號出口，跟隨中強公園指標步行至登山口。'
  },
  {
    id: 'bishanyan',
    name: '碧山巖開漳聖王廟',
    category: 'both',
    lat: 25.0970,
    lng: 121.5878,
    elevation: 250,
    difficulty: '容易（可開車或搭小2公車直達）',
    recommendedFocal: '24-105mm, 70-200mm（飛機與市景）',
    bestAzimuth: '220° - 265°（西南至正西）',
    tags: ['全盆地俯瞰', '松山機場起降', '廟宇平台', '免爬山'],
    description: '內湖半山腰的極致景觀台。廟前大平台可將整座台北盆地、基隆河彎道、松山機場跑道及遠方林口台地盡收眼底。',
    photoTips: '利用中長焦段捕捉民航機在火燒雲背景下起飛或降落的經典剪影瞬間。',
    traffic: '捷運「內湖站」轉乘「小 2 公車」直達碧山巖停車場，步行 3 分鐘即可登上廟前觀景台。'
  },
  {
    id: 'datunshan',
    name: '大屯山助航站觀景台',
    category: 'sunset',
    lat: 25.1764,
    lng: 121.5226,
    elevation: 1070,
    difficulty: '容易至中等（公路可達/需注意山路霧氣）',
    recommendedFocal: '16-35mm, 70-200mm（雲海浪湧）',
    bestAzimuth: '260° - 305°（面迎淡水河口與面天山）',
    tags: ['海拔千米', '秋冬雲海', '芒草金光', '氣勢磅礴'],
    description: '大台北地區最高海拔之車行觀景點！秋冬季節極易遇見壯闊雲海，夕陽將整片雲浪染成翻滾的金色熔岩。',
    photoTips: '山頂風大溫差大，請備妥防風保暖衣物與穩固三腳架。秋季可將金黃色芒草作為前景。',
    traffic: '沿陽金公路轉巴拉卡公路，經大屯山車道直達山頂助航站停車場。'
  },
  {
    id: 'jinmianshan',
    name: '內湖金面山剪刀石',
    category: 'sunset',
    lat: 25.0906,
    lng: 121.5694,
    elevation: 258,
    difficulty: '中等偏難（需攀爬砂岩大石壁 30-40 分鐘）',
    recommendedFocal: '14-24mm 超廣角（強烈險峻空間感）',
    bestAzimuth: '235° - 275°（西南西至正西）',
    tags: ['巨石岩稜', '360度環景', '戶外攀登', '張力十足'],
    description: '矗立於山頂的巨大安山岩石群，擁有 360 度無死角環景。站在剪刀石尖端迎著火燒晚霞，極具英雄電影感。',
    photoTips: '以人像坐在巨石邊緣作為主體剪影，背景搭配整片被夕陽燃燒的台北市天際線。下山天黑請務必攜帶頭燈。',
    traffic: '捷運文湖線「西湖站」1 號出口步行約 15 分鐘至環山路一段 136 巷登山口。'
  },
  {
    id: 'rainbow-park',
    name: '彩虹河濱公園（麥帥橋旁）',
    category: 'sunset',
    lat: 25.0560,
    lng: 121.5772,
    elevation: 8,
    difficulty: '極易（河濱平地）',
    recommendedFocal: '16-35mm 廣角（橋樑倒影）',
    bestAzimuth: '250° - 280°（西南西至正西）',
    tags: ['麥帥一二橋', '101倒影', '河道S彎', '好停車'],
    description: '基隆河畔最唯美的S型彎道，在此可同時框入麥帥一橋、麥帥二橋與台北 101，夕陽餘暉灑在平靜水面上美不勝收。',
    photoTips: '推薦在水門階梯或堤防草坡上架設腳架，捕捉夕陽、車流光軌與河面金光倒影。',
    traffic: '松山火車站或捷運松山站步行經饒河夜市至彩虹橋越堤段，或開車停放於彩虹河濱公園停車場。'
  },
  {
    id: 'yuanshan-breeze',
    name: '圓山風景區微風平台',
    category: 'sunset',
    lat: 25.0825,
    lng: 121.5283,
    elevation: 120,
    difficulty: '容易（步道平緩步行約 15 分鐘）',
    recommendedFocal: '24-70mm, 70-200mm',
    bestAzimuth: '240° - 270°（西南西至正西）',
    tags: ['全新觀景台', '大直橋', '圓山大飯店', '開闊木棧道'],
    description: '台北近年全新落成的超人氣木棧觀景平台，正對大直橋、基隆河與台北 101，視野毫無阻礙，看著夕陽漸漸沒入河面。',
    photoTips: '木棧道設計有前突伸展台，日落時分可以拍出人物走向夕陽火燒雲的延伸視覺感。',
    traffic: '搭乘捷運至「劍潭站」2 號出口，從圓山風景區登山口沿好願步道步行約 15 分鐘。'
  },
  {
    id: 'guanyinshan',
    name: '八里觀音山硬漢嶺',
    category: 'both',
    lat: 25.1378,
    lng: 121.4243,
    elevation: 616,
    difficulty: '中等（步道階梯步行約 45-60 分鐘）',
    recommendedFocal: '24-70mm, 70-200mm',
    bestAzimuth: '日出 100°-130° / 日落 280°-320°',
    tags: ['雙首選', '360度無敵視野', '淡水河口', '台北盆地全覽'],
    description: '「走路要找難路走，挑擔要挑重擔挑」。硬漢嶺頂峰為 360 度觀景平台，向東可迎台北盆地破曉晨霞，向西可送台灣海峽壯麗落日。',
    photoTips: '夏季清晨易見基隆山方向升起的火紅朝霞；傍晚則有八里台北港與淡水暮色的雙重視覺饗宴。',
    traffic: '開車或搭乘橘 20 公車至觀音山遊客中心，循硬漢嶺登山步道上山。'
  },
  {
    id: 'nangang-95peak',
    name: '南港山九五峰',
    category: 'sunrise',
    lat: 25.0315,
    lng: 121.5886,
    elevation: 375,
    difficulty: '中等（石階步道約 45 分鐘）',
    recommendedFocal: '16-35mm, 50mm 定焦',
    bestAzimuth: '70° - 105°（東北東至東南東，迎接晨曦）',
    tags: ['日出首選', '南港山最高點', '破曉金光', '俯瞰台北'],
    description: '南港山系最高峰，巨石上刻有「九五峰」朱紅大字。清晨在此可見東方山脈層次分明的破曉朝霞，萬丈金光灑滿台北盆地。',
    photoTips: '日出前 40 分鐘即需就位，晨曦時天空從深邃紫紅過渡到熾熱金黃的漸變過程最為迷人。',
    traffic: '搭乘捷運至「後山埤站」或「象山站」，從奉天宮登山口或慈惠堂步道起登。'
  },
  {
    id: 'xizhi-dajian',
    name: '汐止大尖山涼亭觀景台',
    category: 'sunrise',
    lat: 25.0483,
    lng: 121.6644,
    elevation: 460,
    difficulty: '容易至中等（天秀宮步行約 20 分鐘）',
    recommendedFocal: '70-200mm（捕捉基隆嶼朝霞）',
    bestAzimuth: '65° - 95°（正東偏北，直視基隆嶼海面）',
    tags: ['基隆嶼晨曦', '海面朝霞', '汐止地標', '東方第一道光'],
    description: '汐止著名的日出機位！天氣通透時，可遠眺基隆嶼與野柳岬海面，清晨東方海平面的朝霞將基隆嶼勾勒出絕美剪影。',
    photoTips: '晨霞往往在太陽露出海平面之前 20-30 分鐘最為血紅艷麗，建議攜帶長焦鏡頭特寫海面晨光。',
    traffic: '由汐止火車站搭乘 F911 汐止區免費社區巴士至「天秀宮」，再循步道登頂。'
  },
  {
    id: 'maokong-zhinan',
    name: '木柵貓空指南宮凌霄寶殿',
    category: 'both',
    lat: 24.98421427814147,
    lng: 121.58655991120213,
    elevation: 280,
    difficulty: '極易（貓空纜車直達指南宮站）',
    recommendedFocal: '24-70mm（宮殿與夕陽晚霞合影）',
    bestAzimuth: '280° - 315°（西北西夕照）',
    tags: ['貓空纜車', '道教古殿', '茶園山嵐', '古典韻味'],
    description: '宏偉的道教宮殿與群山夕陽晚霞相互輝映。站在凌霄寶殿長廊，夕陽餘暉穿透飛簷斗拱，伴隨裊裊香煙，宛如仙境。',
    photoTips: '以宮殿金色琉璃瓦與雕花欄杆作為前景框架，側光拍攝夕陽打在建築上的金黃光影。',
    traffic: '搭乘捷運文湖線至「動物園站」，轉乘「貓空纜車」至「指南宮站」即達。'
  },
  {
    id: 'jiufen-buyan',
    name: '新北九份與不厭亭觀景台',
    category: 'both',
    lat: 25.110048954642046,
    lng: 121.83829071730524,
    elevation: 530,
    difficulty: '公路旁需自駕或搭乘公車',
    recommendedFocal: '70-200mm 望遠, 24-70mm',
    bestAzimuth: '日落 290° / 日出 80°',
    tags: ['寂寞公路', '山海交界', '雲海晨昏', '芒草金光'],
    description: '雙溪與瑞芳交界的寂寞公路，山脊線兩側海天一色，火燒雲常伴隨奔騰雲海，山海交界落日氣勢磅礴。',
    photoTips: '102 縣道山脊線可俯瞰全景，秋季芒草金光與夕陽火燒雲形成絕美對比。',
    traffic: '搭乘 788/965 公車至九份老街，或自駕沿 102 縣道行駛至不厭亭。'
  }
];

if (typeof window !== 'undefined') {
  window.TAIPEI_SPOTS = TAIPEI_SPOTS;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = TAIPEI_SPOTS;
}
